before_script:
  - pip install virtualenv
  - virtualenv -p "$(which python)" /tmp/test

stages:
  - code-quality

pytest:
  image: registry.nic.cz/turris/foris-ci/python3
  stage: code-quality
  script:
    - source /tmp/test/bin/activate
    - pip install tox
    - tox
  artifacts:
    reports:
      junit: report.xml
      cobertura: coverage.xml
  coverage: /^TOTAL.*\s+([^\s]+)%$/

pre-commit:
  image: registry.nic.cz/turris/foris-ci/python3
  stage: code-quality
  script:
    - source /tmp/test/bin/activate
    - pip install .[dev]
    - pre-commit run --hook-stage push --all-files
