before_script:
  - pip install virtualenv
  - virtualenv -p "$(which python)" /tmp/test

stages:
  - image
  - code-quality

test_image:
  image: docker:git
  stage: image
  services:
  - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $CI_REGISTRY_IMAGE/test:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/test:latest --tag $CI_REGISTRY_IMAGE/test:latest --target test .
    - docker push $CI_REGISTRY_IMAGE/test:latest

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

  tags:
    - dind


pytest:
  image: registry.labs.nic.cz/turris/foris-controller/foris-forwarder/test
  stage: code-quality
  script:
    - source /tmp/test/bin/activate
    - pip install .
    - python setup.py test

pre-commit:
  image: registry.labs.nic.cz/turris/foris-ci/python3
  stage: code-quality
  script:
    - source /tmp/test/bin/activate
    - pip install .[dev]
    - pre-commit run --hook-stage push --all-files
