default_stages: [push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        types: [python]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        types: [python]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.1.0
    hooks:
    -   id: isort
        types: [python]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        types: [python]
